In [ ]:
import numpy as np

a=np.array([[0,1],[2,3],[4,5]])
b=np.array([[0,1,2,3],[4,5,6,7]])
multi_value=np.dot(a,b)
print(multi_value)

max_value=multi_value.max()

print(max_value)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
[20 29 38 47]
[ 7 27 47]
